# Generated by Django 5.2.5 on 2025-09-07 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrier',
            name='address',
        ),
        migrations.RemoveField(
            model_name='carrier',
            name='notes',
        ),
        migrations.AddField(
            model_name='carrier',
            name='rates',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
