# Generated by Django 5.0.14 on 2025-09-12 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0002_remove_carrier_address_remove_carrier_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrier',
            name='rates',
        ),
        migrations.AddField(
            model_name='carrier',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='carrier.carrier')),
            ],
        ),
    ]
