# Generated by Django 5.2.5 on 2025-09-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('po_number', models.CharField(max_length=50)),
                ('ship_date', models.DateField(blank=True, null=True)),
                ('order_number', models.CharField(blank=True, max_length=50, null=True)),
                ('location_from', models.CharField(blank=True, max_length=200, null=True)),
                ('location_to', models.CharField(blank=True, max_length=200, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
