# Generated by Django 5.2.5 on 2025-09-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_location_to_order_carrier_order_shipped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipped',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10),
        ),
    ]
