steps:
# 1. Build the container image using the Dockerfile
# '.' means use the Dockerfile in the current directory (root of the repo)
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/my-service:$COMMIT_SHA'  # AR path + tag
    - '.'

# 2. Push the newly built image to Artifact Registry
# The image name here must exactly match the image name in the build step
images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/my-service:$COMMIT_SHA'

# 3. Required options for the custom service account
# This fixes the "must use CLOUD_LOGGING_ONLY" error.
options:
  logging: CLOUD_LOGGING_ONLY
