version: "3.9"

services:
  web:
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - pg
    env_file:
      - .env
    restart: unless-stopped

  pg:
    container_name: carrier-pg
    image: postgres:14.1-alpine3.15
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data


  pgadmin:
    container_name: carrier-pgadmin
    image: dpage/pgadmin4:6.4
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8082:80"
    depends_on:
      - pg

volumes:
  postgres_data:
